#! /bin/bash

root_dir=.
model_dir=${root_dir}/MF_model
output_dir=${root_dir}/output

if [ ! -d $model_dir ];
then
	mkdir $model_dir
fi

if [ ! -d $output_dir ];
then
	mkdir $output_dir
fi

if [ $1 == "sample" ]; 
then
	echo "run createData.py"
	# because there is no suitable data for me to do my product
	# I random the dataset with certain distribution myself. 
	python3 src/createData.py 

elif [ $1 == "eval" ]; 
then
	echo "run evalModel.py"
	# this python is to evaluate whether the MF model is good enough
	python3 src/evalModel.py

elif [ $1 == "analysis" ]; 
then
	echo "run dataAnalyzer.py"
	# analyize the data, including the consumers with account or not
	# to cluster the author by user preference
	# and store the model and information file in model/ and output/,
	# separately. The process of training model is quite time-consuming.
	python3 src/dataAnalyzer.py
elif [ $1 == "forecast" ];
then
	echo "run forecastRecommender.py"
	# when the manager have to make the demand forecast strategy
	# this python will help collect the data from the platform
	# and predict the volume to buy based on the model generated 
	# from dataAnalyzrt.py
	python3 src/forecastRecommender.py

elif [ $1 == "go" ];
then
	# here is to run the complete process flow of the product
	echo "============= process flow =============="
	echo "---------- run createData.py ------------"
	python3 src/createData.py
	echo "--------- run dataAnalyzer.py -----------"
	time python3 src/dataAnalyzer.py
	echo "------ run forecastRecommender.py -------"
	python3 src/forecastRecommender.py
elif [ $1 == "clean" ];
then
	echo "-------------- remove data --------------"
	# remove all the data generated by my program
	rm -rf data/Frank*
	rm -rf output/*
	rm -rf MF_model/*
elif [ $1 == "demo" ];
then
	echo "--------------- demo time ---------------"
	python3 src/demo.py 
else
	echo "one argument is needed"
fi
